# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Terminal"
license = "MIT"
licenselink = "https://github.com/fote/terminal-hugo-theme/blob/master/LICENSE.md"
description = "terminal style in hugo"
homepage = "http://4te.me/"
tags = ["terminal", "hugo"]
min_version = 0.14

[author]
  name = "Roman Orlov"
  homepage = "http://4te.me"
