baseurl = "https://4te.me/"
languageCode = "en-us"
title = "/4te.me"
theme = "purehugo"
disqusShortname = "4te"
googleAnalitycs = "UA-82262003-1"
Paginate = 10


[params]
 subtitle = "Любую проблему можно решить bash-однострочником"
 description = "Блог про linux и окололинуксовые темы"
 author = "Roman Orlov"
 hideShareOptions = true
